# Generated by Django 2.0.6 on 2018-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replica',
            name='description',
            field=models.TextField(blank=True, help_text='describe the replica or machine resources and host', max_length=512),
        ),
        migrations.AlterField(
            model_name='replica',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='the external IP address replicas can connect to', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='replica',
            name='precedence',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='the precedence of the replica over other replicas (PID)'),
        ),
    ]
