development: &default
  <<: *default
  adapter: postgresql
  database: kahu_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  prepared_statements: false

test:
  <<: *default
  database: kahu_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
