# Generated by Django 2.0.6 on 2018-06-11 20:20

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('operation', models.CharField(help_text='unique name of the boto operation being cached', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'boto_cache',
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='RegionCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('region', models.CharField(help_text='name of the region the request was made to', max_length=255)),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='the actual cached data from the Boto3 response', null=True)),
                ('error', models.CharField(blank=True, default='', editable=False, help_text='any error or exception raised during the operation', max_length=255, null=True)),
                ('operation', models.ForeignKey(help_text='the associated operation the data is being stored for', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geonet.BotoCache')),
            ],
            options={
                'db_table': 'boto_region_cache',
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterUniqueTogether(
            name='regioncache',
            unique_together={('region', 'operation')},
        ),
    ]
