# Generated by Django 2.0.6 on 2018-06-14 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('replicas', '0003_update_latency_meta'),
        ('geonet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSInstance',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('replica', models.OneToOneField(help_text='the replica assoicated with the AWS instance', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aws_instance', serialize=False, to='replicas.Replica')),
                ('instance_id', models.CharField(help_text='the AWS instance id to perform AWS queries on', max_length=255, unique=True, verbose_name='Instance ID')),
                ('instance_type', models.CharField(blank=True, default='', help_text='the AWS instance type/size e.g. t2.medium', max_length=255, null=True)),
                ('availability_zone', models.CharField(blank=True, default='', help_text='the AWS availability zone the instance is located in', max_length=255, null=True)),
                ('launch_time', models.DateTimeField(blank=True, help_text='the timestamp that the instance was launched', null=True)),
            ],
            options={
                'verbose_name': 'AWS Instance',
                'verbose_name_plural': 'AWS Instances',
                'db_table': 'aws_instances',
                'ordering': ('-modified',),
                'get_latest_by': 'modified',
            },
        ),
    ]
